OPENAI_API_KEY = "sk-7eDjQUm6YuRxh-GMk6dyMg"
OPENAI_BASE_URL = "https://ai.sumopod.com/v1"
SUPABASE_URL = "https://yxzikmwomgbdcvepxplm.supabase.co"
SUPABASE_KEY = "sb_publishable_J7Y7bzL_3Crrjs6hmHNVdg_EZCjtUyc"